name: runner

# on:
#   schedule:
#   - cron: "0 */8 * * *" # every 8h

on: push

jobs:
  build:
    name: Build docker-compose 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: env SERVER_SRC=./impl-endpoints SERVER=boringssl CLIENT_SRC=./regression-endpoints CLIENT=tlsfuzzer docker-compose build
  build-and-run:
    name: Build and run interop runner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make runner
  # run:
  #   needs: [ build ]
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-go@v2
  #   - run: make interop
