name: runner

# on:
#   schedule:
#   - cron: "0 */8 * * *" # every 8h

on: push

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make runner
  run:
    needs: [ build ]
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make runner 
    - run: ./bin/runner
